# backend/Dockerfile.dev

FROM azul/zulu-openjdk:26 AS build
RUN apt-get update && apt-get install -y maven
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY . .
CMD ["mvn", "spring-boot:run"]