# backend/Dockerfile.dev

FROM azul/zulu-openjdk:26 AS build
RUN apt-get update && apt-get install -y maven
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY . .
# nincs már wsl2, ezért a watcher ránéz a kódra x másodpercenként, hogy van-e változás és indít egy rebuildet, ha igen
RUN chmod +x compile-watch.sh
CMD ["sh", "-c", "./compile-watch.sh & exec mvn spring-boot:run"]