package com.starbuck.moneytracker.entity;

import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

@Entity(name = "transaction_details")
public class TransactionDetail {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = true)
    private Double price;

    @Column(nullable = true)
    private Double weight;

    @Column(nullable = true)
    private Double unitPrice;

    // TODO category field

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    @ManyToOne
    @JoinColumn(name = "transaction_id", nullable = false)
    private Transaction transaction;

    /**
     * Visszatér a tranzakció összegével
     * 
     * @return
     */
    public double getCost() {
        if (this.getPrice() != null) {
            return this.getPrice();
        } else if (this.getWeight() != null && this.getUnitPrice() != null) {
            return this.calculateCostFromUnitPriceAndWeight();
        } else {
            throw new IllegalStateException(
                    "Price is null and weight or unitPrice is not defined for TransactionDetail with ID: " + this.id);
        }
    }

    /**
     * Visszatér a tranzakció összegével, a súly és egységár használatával
     * 
     * @return
     */
    public double calculateCostFromUnitPriceAndWeight() {
        if (this.getWeight() == null || this.getUnitPrice() == null) {
            throw new IllegalStateException(
                    "TransactionDetail must have both weight and unitPrice defined to calculate cost.");
        }

        return this.getWeight() * this.getUnitPrice();
    }

    // AUTOGENERATED

    public TransactionDetail() {
    }

    public TransactionDetail(Long id, Long transaction_id, String name, Double price, Double weight, Double unitPrice,
            LocalDateTime createdAt, LocalDateTime updatedAt, Transaction transaction) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.weight = weight;
        this.unitPrice = unitPrice;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.transaction = transaction;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Transaction getTransaction() {
        return transaction;
    }

    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
}
