package com.starbuck.moneytracker.entity;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Set;

import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;
import org.hibernate.annotations.UpdateTimestamp;

import com.starbuck.moneytracker.service.TransactionService;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

// soft delete
@SQLDelete(sql = "UPDATE transactions SET status = 1 WHERE id = ?")
// autogenerált sql-ekben csak a nem töröltek jelennek meg
@SQLRestriction("status = 0")
@Entity
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private LocalDate transactionDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionTypeEnum transactionType;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal priceSum;

    @Column(nullable = false)
    @ColumnDefault("0") // todo legyen enum
    private int status;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    @OneToMany(mappedBy = "transaction")
    private Set<TransactionDetail> transactionDetails;

    @ManyToOne(optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Törölt-e a tranzakció
     * 
     * @return boolean
     */
    public boolean isDeleted() {
        return this.status == 1;
    }

    /**
     * Tranzakcióhoz tartozó tételek összértékét adja vissza
     * 
     * @return
     */
    public BigDecimal sumDetailsCost() {
        return this.transactionDetails.stream().map(TransactionDetail::getCost).reduce(BigDecimal.ZERO, BigDecimal::add)
                .setScale(2, RoundingMode.HALF_UP);
    }

    /**
     * Meghatározza, hogy a tranzakció komplex-e, azaz több tételből áll-e, vagy egy
     * tétel van, de annak a neve kézzel lett felvéve
     * 
     * @return
     */
    public boolean getIsComplexTransaction() {
        return this.transactionDetails.size() > 1
                || !this.transactionDetails.iterator().next().getName().equals(TransactionService.DEFAULT_DETAIL_NAME);
    }

    // AUTOGENERATED

    public Transaction() {
    }

    public Transaction(Long id, String name, LocalDate transactionDate, TransactionTypeEnum transactionType,
            BigDecimal priceSum,
            int status) {
        this.id = id;
        this.name = name;
        this.transactionDate = transactionDate;
        this.transactionType = transactionType;
        this.priceSum = priceSum;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    public TransactionTypeEnum getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(TransactionTypeEnum transactionType) {
        this.transactionType = transactionType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Set<TransactionDetail> getTransactionDetails() {
        return transactionDetails;
    }

    public void setTransactionDetails(Set<TransactionDetail> transactionDetails) {
        this.transactionDetails = transactionDetails;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public BigDecimal getPriceSum() {
        return priceSum;
    }

    public void setPriceSum(BigDecimal priceSum) {
        this.priceSum = priceSum;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
}
