package com.starbuck.moneytracker.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;
import org.hibernate.annotations.UpdateTimestamp;

import com.starbuck.moneytracker.entity.enum_entites.TransactionTypeEnum;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

// soft delete
@SQLDelete(sql = "UPDATE transactions SET status = 1 WHERE id = ?")
// autogenerált sql-ekben csak a nem töröltek jelennek meg
@SQLRestriction("status = 0")
@Entity
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private LocalDate transactionDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionTypeEnum transactionType;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal priceSum;

    @Column(nullable = false)
    @ColumnDefault("0") // TODO legyen GeneralStatusEnum
    private int status;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    @OneToMany(mappedBy = "transaction")
    private List<TransactionDetail> transactionDetails;

    @ManyToOne(optional = false)
    @JoinColumn(name = "wallet_id", nullable = false)
    private Wallet wallet;

    /**
     * Törölt-e a tranzakció
     * 
     * @return boolean
     */
    public boolean isDeleted() {
        return this.status == 1;
    }

    /**
     * Meghatározza, hogy a tranzakció komplex-e, azaz több tételből áll-e, vagy egy
     * tétel van, de annak a neve kézzel lett felvéve
     * 
     * @return
     */
    public boolean isComplexTransaction() {
        if (transactionDetails == null || transactionDetails.isEmpty()) {
            return false;
        }

        if (transactionDetails.size() > 1) {
            return true;
        }

        String name = this.transactionDetails.iterator().next().getName();
        return !TransactionDetail.DEFAULT_DETAIL_NAME.equals(name);
    }

    /**
     * Kiadás-e az adott tranzakció
     * 
     * @return
     */
    public boolean isOutcome() {
        return this.transactionType.equals(TransactionTypeEnum.OUTCOME);
    }

    // AUTOGENERATED

    public Transaction() {
    }

    public Transaction(Long id, String name, LocalDate transactionDate, TransactionTypeEnum transactionType,
            BigDecimal priceSum,
            int status) {
        this.id = id;
        this.name = name;
        this.transactionDate = transactionDate;
        this.transactionType = transactionType;
        this.priceSum = priceSum;
        this.status = status;
    }

    public Transaction(String name, LocalDate transactionDate, TransactionTypeEnum transactionType,
            BigDecimal priceSum) {
        this.name = name;
        this.transactionDate = transactionDate;
        this.transactionType = transactionType;
        this.priceSum = priceSum;
    }

    public Transaction(String name, LocalDate transactionDate, TransactionTypeEnum transactionType,
            BigDecimal priceSum, Wallet wallet) {
        this.name = name;
        this.transactionDate = transactionDate;
        this.transactionType = transactionType;
        this.priceSum = priceSum;
        this.wallet = wallet;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    public TransactionTypeEnum getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(TransactionTypeEnum transactionType) {
        this.transactionType = transactionType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<TransactionDetail> getTransactionDetails() {
        return transactionDetails;
    }

    public void setTransactionDetails(List<TransactionDetail> transactionDetails) {
        this.transactionDetails = transactionDetails;
    }

    public BigDecimal getPriceSum() {
        return priceSum;
    }

    public void setPriceSum(BigDecimal priceSum) {
        this.priceSum = priceSum;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Wallet getWallet() {
        return wallet;
    }

    public void setWallet(Wallet wallet) {
        this.wallet = wallet;
    }
}
