INSERT INTO category (name) VALUES 
('in_db.category.food'),
('in_db.category.household'),
('in_db.category.hygiene'),
('in_db.category.health'),
('in_db.category.transport'),
('in_db.category.fuel'),
('in_db.category.entertainment'),
('in_db.category.clothing'),
('in_db.category.electronics'),
('in_db.category.home'),
('in_db.category.pets'),
('in_db.category.gifts'),
('in_db.category.education'),
('in_db.category.sport'),
('in_db.category.subscription'),
('in_db.category.other');
